// Update integrity checks.
//
// KubePilot releases are not code-signed (electron-builder runs with no
// signing identity), so the strongest check the release pipeline supports is
// the SHA-256 of each installer, published twice by GitHub itself:
//   * the asset's `digest` ("sha256:…") in the Releases API, computed by
//     GitHub when the file was uploaded, and
//   * SHA256SUMS.txt, generated by .github/workflows/release.yml from the
//     very files it uploads.
// Both must agree when both exist, at least one must exist, and the
// downloaded bytes must match — otherwise nothing is installed.
import crypto from 'node:crypto';
import fs from 'node:fs';
import { updateError } from './errors.mjs';

export const CHECKSUMS_ASSET = 'SHA256SUMS.txt';
const HEX64 = /^[0-9a-f]{64}$/;

/** Parse `sha256sum` output ("<hex>  <name>" or "<hex> *<name>") → Map(name → hex). */
export function parseChecksums(text) {
  const out = new Map();
  for (const line of String(text || '').split(/\r?\n/)) {
    const m = line.trim().match(/^([0-9a-fA-F]{64})\s+\*?(.+)$/);
    if (m) out.set(m[2].trim(), m[1].toLowerCase());
  }
  return out;
}

/**
 * The SHA-256 the asset must have: { sha256, sources: ['github-digest', 'SHA256SUMS.txt'] }.
 * Throws verification_unavailable when the release publishes no checksum for
 * it, and verification_failed when the two published checksums disagree.
 */
export function expectedSha256(asset, checksums) {
  const fromApi = asset?.digest && HEX64.test(asset.digest) ? asset.digest : null;
  const fromFile = checksums instanceof Map ? checksums.get(asset?.name) || null : null;
  if (fromApi && fromFile && fromApi !== fromFile) {
    throw updateError('verification_failed', undefined, {
      detail: `published checksums disagree for ${asset.name}`,
    });
  }
  const sha256 = fromApi || fromFile;
  if (!sha256) {
    throw updateError(
      'verification_unavailable',
      `The update ${asset?.name || ''} can't be verified because the release publishes no checksum for it, so it will not be installed.`.replace(
        '  ',
        ' '
      ),
      { detail: 'no digest and no SHA256SUMS.txt entry' }
    );
  }
  return { sha256, sources: [fromApi && 'github-digest', fromFile && CHECKSUMS_ASSET].filter(Boolean) };
}

/** Constant-time comparison of two hex digests. */
export function digestsMatch(a, b) {
  if (
    typeof a !== 'string' ||
    typeof b !== 'string' ||
    !HEX64.test(a.toLowerCase()) ||
    !HEX64.test(b.toLowerCase())
  )
    return false;
  return crypto.timingSafeEqual(Buffer.from(a.toLowerCase(), 'hex'), Buffer.from(b.toLowerCase(), 'hex'));
}

/** SHA-256 (hex) of a file, streamed. */
export function sha256File(file) {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash('sha256');
    fs.createReadStream(file)
      .on('error', reject)
      .on('data', (c) => hash.update(c))
      .on('end', () => resolve(hash.digest('hex')));
  });
}
